#pragma once

/* IPC operation is a 32-bit integer value delivered to the server.
 * The top 24 bits define class + method, which tell the server what we want
 * to do. (Someday I'll standardise these.)
 */
#define IPC_CLASS_MASK          0xffff0000
#define IPC_CLASS_SHIFT         16
#define IPC_METHOD_MASK         0x0000ff00
#define IPC_METHOD_SHIFT        8
#define IPC_MODE_MASK           0x000000ff
#define IPC_MODE_SHIFT          0

/* System messages, generated by the kernel */
#define IPC_CLASS_SYSTEM        0
#define IPC_SYSTEM_READ         ( 1 << IPC_METHOD_SHIFT)
#define IPC_SYSTEM_WRITE        ( 2 << IPC_METHOD_SHIFT)

/* Bottom 8 bits tell the kernel how to deliver the message
 *  - txstr     copy a string (memory slice) into the server address space
 *  - rxstr     allow the server to respond with a string
 *  - fragment  allow the kernel to send only part of the message, if there
 *              is not enough space in the server's string receive area
 *
 * TODO: bits for copying file descriptors
 */
#define IPC_CALL_TXSTR          0x01
#define IPC_CALL_RXSTR          0x02
#define IPC_CALL_FRAGMENT       0x04
#define IPC_CALL_RXOPEN         0x08


#define IPC_TRANSFER_REGISTER   0
#define IPC_TRANSFER_SMALLSTR   1
#define IPC_TRANSFER_LARGESTR   2
#define IPC_TRANSFER_READ       3
#define IPC_TRANSFER_WRITE      4
